export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILED = 'FETCH_ITEMS_FAILED';

export const SAVE_ITEMS = 'SAVE_ITEMS';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';

export const FETCH_DESCRIPTION_REQUEST = 'FETCH_DESCRIPTION_REQUEST';
export const FETCH_DESCRIPTION_SUCCESS = 'FETCH_DESCRIPTION_SUCCESS';
export const FETCH_DESCRIPTION_FAILED = 'FETCH_DESCRIPTION_FAILED';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';
