export const SEARCH_INPUT_CHANGED = 'SEARCH_INPUT_CHANGED';
export const SAVE_SEARCH_DATA = 'SAVE_SEARCH_DATA';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';

export const TOGGLE_FETCH = 'TOGGLE_FETCH';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
